"""Blocos da footage (W2.B): do roteiro anotado aos spans, ao plano de ritmo e ao `_base`.

Os cenários golden vêm do MAIN do `produzir_roteiro.py` ORIGINAL (commit 2ebd1cc) executado até
a decisão de `_base`, com o parser e o alinhamento trocados por dados sintéticos: mesma entrada,
mesmos blocos, spans, palavras por bloco, plano de ritmo e escala. Nada aqui roda ffmpeg.
"""
import json
from pathlib import Path

import pytest

from audio import transcrever as T
from footage import blocos as BL
from footage import cadeia as CA

# nome -> {blocos_entrada, palavras, inserts, blocks, spans, bwords, plano, bases, ritmo_json}
GOLDEN_CENARIOS = {'apresentadores_seguidos': {'blocos_entrada': [{'instr': 'apresentador',
                                                 'key': '',
                                                 'lead': '',
                                                 'narr': 'primeiro bloco da fala com algumas '
                                                         'palavras suficientes para dividir',
                                                 'type': 'orig',
                                                 'zoom': False},
                                                {'instr': 'apresentador',
                                                 'key': '',
                                                 'lead': '',
                                                 'narr': 'segundo bloco da fala também com algumas '
                                                         'palavras para dividir em planos',
                                                 'type': 'orig',
                                                 'zoom': False},
                                                {'instr': 'apresentador + lettering',
                                                 'key': 'CURTO',
                                                 'lead': '',
                                                 'narr': 'terceiro bloco curto',
                                                 'type': 'lettering',
                                                 'zoom': False},
                                                {'instr': 'apresentador',
                                                 'key': '',
                                                 'lead': '',
                                                 'narr': 'quarto bloco de fecho das ideias '
                                                         'principais do roteiro de teste',
                                                 'type': 'orig',
                                                 'zoom': False}],
                             'palavras': [[0.0, 0.288, 'primeiro'],
                                          [0.32, 0.608, 'bloco'],
                                          [0.64, 0.928, 'da'],
                                          [0.96, 1.248, 'fala'],
                                          [1.28, 1.568, 'com'],
                                          [1.6, 1.888, 'algumas'],
                                          [1.92, 2.208, 'palavras'],
                                          [2.24, 2.528, 'suficientes'],
                                          [2.56, 2.848, 'para'],
                                          [2.88, 3.168, 'dividir'],
                                          [3.3, 3.588, 'segundo'],
                                          [3.62, 3.908, 'bloco'],
                                          [3.94, 4.228, 'da'],
                                          [4.26, 4.548, 'fala'],
                                          [4.58, 4.868, 'também'],
                                          [4.9, 5.188, 'com'],
                                          [5.22, 5.508, 'algumas'],
                                          [5.54, 5.828, 'palavras'],
                                          [5.86, 6.148, 'para'],
                                          [6.18, 6.468, 'dividir'],
                                          [6.5, 6.788, 'em'],
                                          [6.82, 7.108, 'planos'],
                                          [7.24, 7.528, 'terceiro'],
                                          [7.56, 7.848, 'bloco'],
                                          [7.88, 8.168, 'curto'],
                                          [8.3, 8.588, 'quarto'],
                                          [8.62, 8.908, 'bloco'],
                                          [8.94, 9.228, 'de'],
                                          [9.26, 9.548, 'fecho'],
                                          [9.58, 9.868, 'das'],
                                          [9.9, 10.188, 'ideias'],
                                          [10.22, 10.508, 'principais'],
                                          [10.54, 10.828, 'do'],
                                          [10.86, 11.148, 'roteiro'],
                                          [11.18, 11.468, 'de'],
                                          [11.5, 11.788, 'teste']],
                             'inserts': {},
                             'blocks': [{'_base': 1.0,
                                         'instr': 'apresentador',
                                         'key': '',
                                         'lead': '',
                                         'narr': 'primeiro bloco da fala com algumas palavras '
                                                 'suficientes para dividir',
                                         'type': 'orig',
                                         'zoom': False},
                                        {'_base': 1.14,
                                         'instr': 'apresentador',
                                         'key': '',
                                         'lead': '',
                                         'narr': 'segundo bloco da fala também com algumas '
                                                 'palavras para dividir em planos',
                                         'type': 'orig',
                                         'zoom': False},
                                        {'_base': 1.0,
                                         'instr': 'apresentador + lettering',
                                         'key': 'CURTO',
                                         'lead': '',
                                         'narr': 'terceiro bloco curto',
                                         'type': 'lettering',
                                         'zoom': False},
                                        {'_base': 1.14,
                                         'instr': 'apresentador',
                                         'key': '',
                                         'lead': '',
                                         'narr': 'quarto bloco de fecho das ideias principais do '
                                                 'roteiro de',
                                         'type': 'orig',
                                         'zoom': False}],
                             'spans': [[0.0, 3.3], [3.3, 7.24], [7.24, 8.3], [8.3, 11.788]],
                             'bwords': [[[0.0, 0.288],
                                         [0.32, 0.608],
                                         [0.64, 0.928],
                                         [0.96, 1.248],
                                         [1.28, 1.568],
                                         [1.6, 1.888],
                                         [1.92, 2.208],
                                         [2.24, 2.528],
                                         [2.56, 2.848],
                                         [2.88, 3.168]],
                                        [[3.3, 3.588],
                                         [3.62, 3.908],
                                         [3.94, 4.228],
                                         [4.26, 4.548],
                                         [4.58, 4.868],
                                         [4.9, 5.188],
                                         [5.22, 5.508],
                                         [5.54, 5.828],
                                         [5.86, 6.148],
                                         [6.18, 6.468],
                                         [6.5, 6.788],
                                         [6.82, 7.108]],
                                        [[7.24, 7.528], [7.56, 7.848], [7.88, 8.168]],
                                        [[8.3, 8.588],
                                         [8.62, 8.908],
                                         [8.94, 9.228],
                                         [9.26, 9.548],
                                         [9.58, 9.868],
                                         [9.9, 10.188],
                                         [10.22, 10.508],
                                         [10.54, 10.828],
                                         [10.86, 11.148],
                                         [11.18, 11.468]]],
                             'plano': [{'bloco': 0,
                                        'crop': None,
                                        'de': 1,
                                        'e': 3.3,
                                        's': 0.0,
                                        'sub': 0,
                                        'tipo': 'orig'},
                                       {'bloco': 1,
                                        'crop': None,
                                        'de': 1,
                                        'e': 7.24,
                                        's': 3.3,
                                        'sub': 0,
                                        'tipo': 'orig'},
                                       {'bloco': 2,
                                        'crop': None,
                                        'de': 1,
                                        'e': 8.3,
                                        's': 7.24,
                                        'sub': 0,
                                        'tipo': 'orig'},
                                       {'bloco': 3,
                                        'crop': None,
                                        'de': 1,
                                        'e': 11.788,
                                        's': 8.3,
                                        'sub': 0,
                                        'tipo': 'orig'}],
                             'bases': [1.0, 1.14, 1.0, 1.14]},
 'deitico': {'blocos_entrada': [{'instr': 'inserção de vídeo: tela',
                                 'key': '',
                                 'lead': '',
                                 'narr': 'veja como funciona por dentro e por fora desse sistema '
                                         'todo',
                                 'type': 'insert',
                                 'zoom': False},
                                {'instr': 'apresentador',
                                 'key': '',
                                 'lead': '',
                                 'narr': 'isso que você está vendo na tela agora é a prova de que '
                                         'funciona mesmo',
                                 'type': 'orig',
                                 'zoom': False},
                                {'instr': 'apresentador',
                                 'key': '',
                                 'lead': '',
                                 'narr': 'e foi assim que eu fiz tudo isso em poucas horas de '
                                         'trabalho',
                                 'type': 'orig',
                                 'zoom': False}],
             'palavras': [[0.0, 0.315, 'veja'],
                          [0.35, 0.665, 'como'],
                          [0.7, 1.015, 'funciona'],
                          [1.05, 1.365, 'por'],
                          [1.4, 1.715, 'dentro'],
                          [1.75, 2.065, 'e'],
                          [2.1, 2.415, 'por'],
                          [2.45, 2.765, 'fora'],
                          [2.8, 3.115, 'desse'],
                          [3.15, 3.465, 'sistema'],
                          [3.5, 3.815, 'todo'],
                          [4.15, 4.465, 'isso'],
                          [4.5, 4.815, 'que'],
                          [4.85, 5.165, 'você'],
                          [5.2, 5.515, 'está'],
                          [5.55, 5.865, 'vendo'],
                          [5.9, 6.215, 'na'],
                          [6.25, 6.565, 'tela'],
                          [6.6, 6.915, 'agora'],
                          [6.95, 7.265, 'é'],
                          [7.3, 7.615, 'a'],
                          [7.65, 7.965, 'prova'],
                          [8.0, 8.315, 'de'],
                          [8.35, 8.665, 'que'],
                          [8.7, 9.015, 'funciona'],
                          [9.05, 9.365, 'mesmo'],
                          [9.7, 10.015, 'e'],
                          [10.05, 10.365, 'foi'],
                          [10.4, 10.715, 'assim'],
                          [10.75, 11.065, 'que'],
                          [11.1, 11.415, 'eu'],
                          [11.45, 11.765, 'fiz'],
                          [11.8, 12.115, 'tudo'],
                          [12.15, 12.465, 'isso'],
                          [12.5, 12.815, 'em'],
                          [12.85, 13.165, 'poucas'],
                          [13.2, 13.515, 'horas'],
                          [13.55, 13.865, 'de'],
                          [13.9, 14.215, 'trabalho']],
             'inserts': {'tela': {'file': '/m/t.mp4', 'speed': 1.0, 'start': 0}},
             'blocks': [{'instr': 'inserção de vídeo: tela',
                         'key': '',
                         'lead': '',
                         'narr': 'veja como funciona por dentro e por fora desse sistema todo',
                         'type': 'insert',
                         'zoom': False},
                        {'_base': 1.0,
                         'instr': 'apresentador',
                         'key': '',
                         'lead': '',
                         'narr': 'isso que você está vendo na tela agora',
                         'type': 'orig',
                         'zoom': False},
                        {'_base': 1.06,
                         'instr': 'apresentador',
                         'key': '',
                         'lead': '',
                         'narr': 'é a prova de que funciona mesmo',
                         'type': 'orig',
                         'zoom': False},
                        {'_base': 1.14,
                         'instr': 'apresentador',
                         'key': '',
                         'lead': '',
                         'narr': 'e foi assim que eu fiz tudo isso em poucas horas de',
                         'type': 'orig',
                         'zoom': False}],
             'spans': [[0.0, 4.15], [4.15, 6.925], [6.925, 9.7], [9.7, 14.215]],
             'bwords': [[[0.0, 0.315],
                         [0.35, 0.665],
                         [0.7, 1.015],
                         [1.05, 1.365],
                         [1.4, 1.715],
                         [1.75, 2.065],
                         [2.1, 2.415],
                         [2.45, 2.765],
                         [2.8, 3.115],
                         [3.15, 3.465],
                         [3.5, 3.815]],
                        [[4.15, 4.465],
                         [4.5, 4.815],
                         [4.85, 5.165],
                         [5.2, 5.515],
                         [5.55, 5.865],
                         [5.9, 6.215],
                         [6.25, 6.565],
                         [6.6, 6.915]],
                        [[6.95, 7.265],
                         [7.3, 7.615],
                         [7.65, 7.965],
                         [8.0, 8.315],
                         [8.35, 8.665],
                         [8.7, 9.015],
                         [9.05, 9.365]],
                        [[9.7, 10.015],
                         [10.05, 10.365],
                         [10.4, 10.715],
                         [10.75, 11.065],
                         [11.1, 11.415],
                         [11.45, 11.765],
                         [11.8, 12.115],
                         [12.15, 12.465],
                         [12.5, 12.815],
                         [12.85, 13.165],
                         [13.2, 13.515],
                         [13.55, 13.865]]],
             'plano': [{'bloco': 0,
                        'crop': None,
                        'de': 1,
                        'e': 4.15,
                        's': 0.0,
                        'sub': 0,
                        'tipo': 'insert'},
                       {'base': 1.0,
                        'bloco': 1,
                        'crop': None,
                        'de': 2,
                        'e': 6.925,
                        'punch': False,
                        's': 4.15,
                        'sub': 0,
                        'tipo': 'orig'},
                       {'base': 1.06,
                        'bloco': 1,
                        'crop': None,
                        'de': 2,
                        'e': 9.7,
                        'punch': True,
                        's': 6.925,
                        'sub': 1,
                        'tipo': 'orig'},
                       {'bloco': 2,
                        'crop': None,
                        'de': 1,
                        'e': 14.215,
                        's': 9.7,
                        'sub': 0,
                        'tipo': 'orig'}],
             'bases': [None, 1.0, 1.06, 1.14]},
 'fixture_like': {'blocos_entrada': [{'instr': 'inserção de vídeo: demo a',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'Minha skill de criação de páginas transformou meu '
                                              'Claude em um web designer profissional.',
                                      'type': 'insert',
                                      'zoom': False},
                                     {'instr': 'apresentador de frente para a câmera',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'Agora eu construo minhas páginas em minutos, sem '
                                              'precisar pagar nada mais por isso.',
                                      'type': 'orig',
                                      'zoom': False},
                                     {'instr': 'apresentador + lettering',
                                      'key': 'O MELHOR',
                                      'lead': 'sabe qual é',
                                      'narr': 'Sabe qual é o melhor?',
                                      'type': 'lettering',
                                      'zoom': False},
                                     {'instr': 'inserção de vídeo: demo b',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'Se eu usar um conector que é disponibilizado '
                                              'gratuitamente dentro do Claude,',
                                      'type': 'insert',
                                      'zoom': False},
                                     {'instr': 'apresentador + lettering + logo',
                                      'key': 'PRODUZIR AS PÁGINAS',
                                      'lead': 'eu consigo não só',
                                      'narr': 'eu consigo não só produzir as páginas',
                                      'type': 'lettering_logo',
                                      'zoom': False}],
                  'palavras': [[0.62, 0.926, 'Minha'],
                               [0.96, 1.266, 'skill'],
                               [1.3, 1.606, 'de'],
                               [1.64, 1.946, 'criação'],
                               [1.98, 2.286, 'de'],
                               [2.32, 2.626, 'páginas'],
                               [2.66, 2.966, 'transformou'],
                               [3.0, 3.306, 'meu'],
                               [3.34, 3.646, 'Claude'],
                               [3.68, 3.986, 'em'],
                               [4.02, 4.326, 'um'],
                               [4.36, 4.666, 'web'],
                               [4.7, 5.006, 'designer'],
                               [5.04, 5.346, 'profissional.'],
                               [5.78, 6.086, 'Agora'],
                               [6.12, 6.426, 'eu'],
                               [6.46, 6.766, 'construo'],
                               [6.8, 7.106, 'minhas'],
                               [7.14, 7.446, 'páginas'],
                               [7.48, 7.786, 'em'],
                               [7.82, 8.126, 'minutos,'],
                               [8.16, 8.466, 'sem'],
                               [8.5, 8.806, 'precisar'],
                               [8.84, 9.146, 'pagar'],
                               [9.18, 9.486, 'nada'],
                               [9.52, 9.826, 'mais'],
                               [9.86, 10.166, 'por'],
                               [10.2, 10.506, 'isso.'],
                               [10.74, 11.046, 'Sabe'],
                               [11.08, 11.386, 'qual'],
                               [11.42, 11.726, 'é'],
                               [11.76, 12.066, 'o'],
                               [12.1, 12.406, 'melhor?'],
                               [12.94, 13.246, 'Se'],
                               [13.28, 13.586, 'eu'],
                               [13.62, 13.926, 'usar'],
                               [13.96, 14.266, 'um'],
                               [14.3, 14.606, 'conector'],
                               [14.64, 14.946, 'que'],
                               [14.98, 15.286, 'é'],
                               [15.32, 15.626, 'disponibilizado'],
                               [15.66, 15.966, 'gratuitamente'],
                               [16.0, 16.306, 'dentro'],
                               [16.34, 16.646, 'do'],
                               [16.68, 16.986, 'Claude,'],
                               [17.12, 17.426, 'eu'],
                               [17.46, 17.766, 'consigo'],
                               [17.8, 18.106, 'não'],
                               [18.14, 18.446, 'só'],
                               [18.48, 18.786, 'produzir'],
                               [18.82, 19.126, 'as'],
                               [19.16, 19.466, 'páginas']],
                  'inserts': {'demo a': {'file': '/m/a.mp4', 'speed': 1.0, 'start': 0},
                              'demo b': {'file': '/m/b.mp4',
                                         'speed': 1.0,
                                         'split': True,
                                         'start': 1.0}},
                  'blocks': [{'_layout': 'split',
                              'instr': 'inserção de vídeo: demo a',
                              'key': '',
                              'lead': '',
                              'narr': 'Minha skill de criação de páginas transformou meu Claude em '
                                      'um web',
                              'type': 'insert',
                              'zoom': False},
                             {'_layout': 'cheio',
                              'instr': 'inserção de vídeo: demo a',
                              'key': '',
                              'lead': '',
                              'narr': 'designer profissional.',
                              'type': 'insert',
                              'zoom': False},
                             {'_base': 1.0,
                              'instr': 'apresentador de frente para a câmera',
                              'key': '',
                              'lead': '',
                              'narr': 'Agora eu construo minhas páginas em minutos,',
                              'type': 'orig',
                              'zoom': False},
                             {'_base': 1.06,
                              'instr': 'apresentador de frente para a câmera',
                              'key': '',
                              'lead': '',
                              'narr': 'sem precisar pagar nada mais por isso.',
                              'type': 'orig',
                              'zoom': False},
                             {'_base': 1.14,
                              'instr': 'apresentador + lettering',
                              'key': 'O MELHOR',
                              'lead': 'sabe qual é',
                              'narr': 'Sabe qual é o melhor?',
                              'type': 'lettering',
                              'zoom': False},
                             {'instr': 'inserção de vídeo: demo b',
                              'key': '',
                              'lead': '',
                              'narr': 'Se eu usar um conector que é disponibilizado gratuitamente '
                                      'dentro do Claude,',
                              'type': 'insert',
                              'zoom': False},
                             {'instr': 'apresentador + lettering + logo',
                              'key': 'PRODUZIR AS PÁGINAS',
                              'lead': 'eu consigo não só',
                              'narr': 'eu consigo não só produzir as',
                              'type': 'lettering_logo',
                              'zoom': False}],
                  'spans': [[0.62, 4.82],
                            [4.82, 5.78],
                            [5.78, 8.26],
                            [8.26, 10.74],
                            [10.74, 12.94],
                            [12.94, 17.12],
                            [17.12, 19.466]],
                  'bwords': [[[0.62, 0.926],
                              [0.96, 1.266],
                              [1.3, 1.606],
                              [1.64, 1.946],
                              [1.98, 2.286],
                              [2.32, 2.626],
                              [2.66, 2.966],
                              [3.0, 3.306],
                              [3.34, 3.646],
                              [3.68, 3.986],
                              [4.02, 4.326],
                              [4.36, 4.666]],
                             [[4.7, 5.006], [5.04, 5.346]],
                             [[5.78, 6.086],
                              [6.12, 6.426],
                              [6.46, 6.766],
                              [6.8, 7.106],
                              [7.14, 7.446],
                              [7.48, 7.786],
                              [7.82, 8.126]],
                             [[8.16, 8.466],
                              [8.5, 8.806],
                              [8.84, 9.146],
                              [9.18, 9.486],
                              [9.52, 9.826],
                              [9.86, 10.166],
                              [10.2, 10.506]],
                             [[10.74, 11.046],
                              [11.08, 11.386],
                              [11.42, 11.726],
                              [11.76, 12.066],
                              [12.1, 12.406]],
                             [[12.94, 13.246],
                              [13.28, 13.586],
                              [13.62, 13.926],
                              [13.96, 14.266],
                              [14.3, 14.606],
                              [14.64, 14.946],
                              [14.98, 15.286],
                              [15.32, 15.626],
                              [15.66, 15.966],
                              [16.0, 16.306],
                              [16.34, 16.646],
                              [16.68, 16.986]],
                             [[17.12, 17.426],
                              [17.46, 17.766],
                              [17.8, 18.106],
                              [18.14, 18.446],
                              [18.48, 18.786],
                              [18.82, 19.126]]],
                  'plano': [{'bloco': 0,
                             'crop': None,
                             'de': 1,
                             'e': 4.82,
                             'fonte_off': 0.0,
                             'layout': 'split',
                             's': 0.62,
                             'sub': 0,
                             'tipo': 'insert'},
                            {'bloco': 0,
                             'crop': None,
                             'de': 1,
                             'e': 5.78,
                             'layout': 'cheio',
                             's': 4.82,
                             'sub': 0,
                             'tipo': 'insert'},
                            {'base': 1.0,
                             'bloco': 1,
                             'crop': None,
                             'de': 2,
                             'e': 8.26,
                             'punch': False,
                             's': 5.78,
                             'sub': 0,
                             'tipo': 'orig'},
                            {'base': 1.06,
                             'bloco': 1,
                             'crop': None,
                             'de': 2,
                             'e': 10.74,
                             'punch': True,
                             's': 8.26,
                             'sub': 1,
                             'tipo': 'orig'},
                            {'bloco': 2,
                             'crop': None,
                             'de': 1,
                             'e': 12.94,
                             's': 10.74,
                             'sub': 0,
                             'tipo': 'orig'},
                            {'bloco': 3,
                             'crop': None,
                             'de': 1,
                             'e': 17.12,
                             's': 12.94,
                             'sub': 0,
                             'tipo': 'insert'},
                            {'bloco': 4,
                             'crop': None,
                             'de': 1,
                             'e': 19.466,
                             's': 17.12,
                             'sub': 0,
                             'tipo': 'orig'}],
                  'bases': [None, None, 1.0, 1.06, 1.14, None, None]},
 'insert_longo': {'blocos_entrada': [{'instr': 'apresentador',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'abertura curta aqui agora',
                                      'type': 'orig',
                                      'zoom': False},
                                     {'instr': 'inserção de vídeo: longo',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 '
                                              'p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 '
                                              'p28 p29 p30 p31 p32 p33 p34 p35 p36 p37 p38 p39 p40 '
                                              'p41 p42 p43 p44 p45',
                                      'type': 'insert',
                                      'zoom': False},
                                     {'instr': 'apresentador',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'fecho do anúncio com chamada final',
                                      'type': 'orig',
                                      'zoom': False},
                                     {'instr': 'apresentador + lettering + logo',
                                      'key': 'SAIBA MAIS',
                                      'lead': 'toque em',
                                      'narr': 'toque em saiba mais',
                                      'type': 'lettering_logo',
                                      'zoom': False}],
                  'palavras': [[0.5, 0.77, 'abertura'],
                               [0.8, 1.07, 'curta'],
                               [1.1, 1.37, 'aqui'],
                               [1.4, 1.67, 'agora'],
                               [1.9, 2.17, 'p0'],
                               [2.2, 2.47, 'p1'],
                               [2.5, 2.77, 'p2'],
                               [2.8, 3.07, 'p3'],
                               [3.1, 3.37, 'p4'],
                               [3.4, 3.67, 'p5'],
                               [3.7, 3.97, 'p6'],
                               [4.0, 4.27, 'p7'],
                               [4.3, 4.57, 'p8'],
                               [4.6, 4.87, 'p9'],
                               [4.9, 5.17, 'p10'],
                               [5.2, 5.47, 'p11'],
                               [5.5, 5.77, 'p12'],
                               [5.8, 6.07, 'p13'],
                               [6.1, 6.37, 'p14'],
                               [6.4, 6.67, 'p15'],
                               [6.7, 6.97, 'p16'],
                               [7.0, 7.27, 'p17'],
                               [7.3, 7.57, 'p18'],
                               [7.6, 7.87, 'p19'],
                               [7.9, 8.17, 'p20'],
                               [8.2, 8.47, 'p21'],
                               [8.5, 8.77, 'p22'],
                               [8.8, 9.07, 'p23'],
                               [9.1, 9.37, 'p24'],
                               [9.4, 9.67, 'p25'],
                               [9.7, 9.97, 'p26'],
                               [10.0, 10.27, 'p27'],
                               [10.3, 10.57, 'p28'],
                               [10.6, 10.87, 'p29'],
                               [10.9, 11.17, 'p30'],
                               [11.2, 11.47, 'p31'],
                               [11.5, 11.77, 'p32'],
                               [11.8, 12.07, 'p33'],
                               [12.1, 12.37, 'p34'],
                               [12.4, 12.67, 'p35'],
                               [12.7, 12.97, 'p36'],
                               [13.0, 13.27, 'p37'],
                               [13.3, 13.57, 'p38'],
                               [13.6, 13.87, 'p39'],
                               [13.9, 14.17, 'p40'],
                               [14.2, 14.47, 'p41'],
                               [14.5, 14.77, 'p42'],
                               [14.8, 15.07, 'p43'],
                               [15.1, 15.37, 'p44'],
                               [15.4, 15.67, 'p45'],
                               [16.0, 16.27, 'fecho'],
                               [16.3, 16.57, 'do'],
                               [16.6, 16.87, 'anúncio'],
                               [16.9, 17.17, 'com'],
                               [17.2, 17.47, 'chamada'],
                               [17.5, 17.77, 'final'],
                               [18.0, 18.27, 'toque'],
                               [18.3, 18.57, 'em'],
                               [18.6, 18.87, 'saiba'],
                               [18.9, 19.17, 'mais']],
                  'inserts': {'longo': {'crop': '800:600:10:10',
                                        'dur_max': 3.0,
                                        'file': '/m/l.mp4',
                                        'speed': 1.0,
                                        'split': True,
                                        'start': 0}},
                  'blocks': [{'_base': 1.0,
                              'instr': 'apresentador',
                              'key': '',
                              'lead': '',
                              'narr': 'abertura curta aqui agora',
                              'type': 'orig',
                              'zoom': False},
                             {'_crop': '800:600:10:10',
                              '_layout': 'split',
                              'instr': 'inserção de vídeo: longo',
                              'key': '',
                              'lead': '',
                              'narr': 'p0 p1 p2 p3 p4 p5 p6 p7 p8 p9',
                              'type': 'insert',
                              'zoom': False},
                             {'_base': 1.0,
                              'instr': 'inserção de vídeo: longo',
                              'key': '',
                              'lead': '',
                              'narr': 'p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22',
                              'type': 'orig',
                              'zoom': False},
                             {'_crop': '800:600:10:10',
                              '_layout': 'cheio',
                              'instr': 'inserção de vídeo: longo',
                              'key': '',
                              'lead': '',
                              'narr': 'p23 p24 p25 p26 p27 p28 p29 p30 p31 p32',
                              'type': 'insert',
                              'zoom': False},
                             {'_base': 1.0,
                              'instr': 'inserção de vídeo: longo',
                              'key': '',
                              'lead': '',
                              'narr': 'p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45',
                              'type': 'orig',
                              'zoom': False},
                             {'_base': 1.14,
                              'instr': 'apresentador',
                              'key': '',
                              'lead': '',
                              'narr': 'fecho do anúncio com chamada final',
                              'type': 'orig',
                              'zoom': False},
                             {'instr': 'apresentador + lettering + logo',
                              'key': 'SAIBA MAIS',
                              'lead': 'toque em',
                              'narr': 'toque em saiba',
                              'type': 'lettering_logo',
                              'zoom': False}],
                  'spans': [[0.5, 1.9],
                            [1.9, 4.9],
                            [4.9, 8.95],
                            [8.95, 11.95],
                            [11.95, 16.0],
                            [16.0, 18.0],
                            [18.0, 19.17]],
                  'bwords': [[[0.5, 0.77], [0.8, 1.07], [1.1, 1.37], [1.4, 1.67]],
                             [[1.9, 2.17],
                              [2.2, 2.47],
                              [2.5, 2.77],
                              [2.8, 3.07],
                              [3.1, 3.37],
                              [3.4, 3.67],
                              [3.7, 3.97],
                              [4.0, 4.27],
                              [4.3, 4.57],
                              [4.6, 4.87]],
                             [[4.9, 5.17],
                              [5.2, 5.47],
                              [5.5, 5.77],
                              [5.8, 6.07],
                              [6.1, 6.37],
                              [6.4, 6.67],
                              [6.7, 6.97],
                              [7.0, 7.27],
                              [7.3, 7.57],
                              [7.6, 7.87],
                              [7.9, 8.17],
                              [8.2, 8.47],
                              [8.5, 8.77]],
                             [[8.8, 9.07],
                              [9.1, 9.37],
                              [9.4, 9.67],
                              [9.7, 9.97],
                              [10.0, 10.27],
                              [10.3, 10.57],
                              [10.6, 10.87],
                              [10.9, 11.17],
                              [11.2, 11.47],
                              [11.5, 11.77]],
                             [[11.8, 12.07],
                              [12.1, 12.37],
                              [12.4, 12.67],
                              [12.7, 12.97],
                              [13.0, 13.27],
                              [13.3, 13.57],
                              [13.6, 13.87],
                              [13.9, 14.17],
                              [14.2, 14.47],
                              [14.5, 14.77],
                              [14.8, 15.07],
                              [15.1, 15.37],
                              [15.4, 15.67]],
                             [[16.0, 16.27],
                              [16.3, 16.57],
                              [16.6, 16.87],
                              [16.9, 17.17],
                              [17.2, 17.47],
                              [17.5, 17.77]],
                             [[18.0, 18.27], [18.3, 18.57], [18.6, 18.87]]],
                  'plano': [{'bloco': 0,
                             'crop': None,
                             'de': 1,
                             'e': 1.9,
                             's': 0.5,
                             'sub': 0,
                             'tipo': 'orig'},
                            {'bloco': 1,
                             'crop': '800:600:10:10',
                             'de': 4,
                             'e': 4.9,
                             'fonte_off': 0.0,
                             'layout': 'split',
                             's': 1.9,
                             'sub': 0,
                             'tipo': 'insert'},
                            {'base': 1.0,
                             'bloco': 1,
                             'crop': None,
                             'de': 4,
                             'e': 8.95,
                             's': 4.9,
                             'sub': 1,
                             'tipo': 'orig'},
                            {'bloco': 1,
                             'crop': '800:600:10:10',
                             'de': 4,
                             'e': 11.95,
                             'fonte_off': 0.0,
                             'layout': 'cheio',
                             's': 8.95,
                             'sub': 2,
                             'tipo': 'insert'},
                            {'base': 1.06,
                             'bloco': 1,
                             'crop': None,
                             'de': 4,
                             'e': 16.0,
                             's': 11.95,
                             'sub': 3,
                             'tipo': 'orig'},
                            {'bloco': 2,
                             'crop': None,
                             'de': 1,
                             'e': 18.0,
                             's': 16.0,
                             'sub': 0,
                             'tipo': 'orig'},
                            {'bloco': 3,
                             'crop': None,
                             'de': 1,
                             'e': 19.17,
                             's': 18.0,
                             'sub': 0,
                             'tipo': 'orig'}],
                  'bases': [1.0, None, 1.0, None, 1.0, 1.14, None]},
 'sem_narr_logo': {'blocos_entrada': [{'instr': 'apresentador',
                                       'key': '',
                                       'lead': '',
                                       'narr': 'começo da fala aqui neste momento',
                                       'type': 'orig',
                                       'zoom': False},
                                      {'instr': 'inserção de vídeo: y',
                                       'key': '',
                                       'lead': '',
                                       'narr': '',
                                       'type': 'insert',
                                       'zoom': False},
                                      {'instr': 'logo da marca',
                                       'key': '',
                                       'lead': '',
                                       'narr': 'marca e nome do produto',
                                       'type': 'logo',
                                       'zoom': False},
                                      {'instr': 'apresentador + lettering',
                                       'key': 'DESTAQUE',
                                       'lead': '',
                                       'narr': 'texto de destaque',
                                       'type': 'lettering',
                                       'zoom': False},
                                      {'instr': 'apresentador',
                                       'key': '',
                                       'lead': '',
                                       'narr': 'fecho final da fala completa',
                                       'type': 'orig',
                                       'zoom': False}],
                   'palavras': [[0.0, 0.27, 'começo'],
                                [0.3, 0.57, 'da'],
                                [0.6, 0.87, 'fala'],
                                [0.9, 1.17, 'aqui'],
                                [1.2, 1.47, 'neste'],
                                [1.5, 1.77, 'momento'],
                                [2.0, 2.27, 'marca'],
                                [2.3, 2.57, 'e'],
                                [2.6, 2.87, 'nome'],
                                [2.9, 3.17, 'do'],
                                [3.2, 3.47, 'produto'],
                                [3.7, 3.97, 'texto'],
                                [4.0, 4.27, 'de'],
                                [4.3, 4.57, 'destaque'],
                                [4.8, 5.07, 'fecho'],
                                [5.1, 5.37, 'final'],
                                [5.4, 5.67, 'da'],
                                [5.7, 5.97, 'fala'],
                                [6.0, 6.27, 'completa']],
                   'inserts': {'y': {'file': '/m/y.mp4', 'speed': 1.0, 'start': 0}},
                   'blocks': [{'_base': 1.0,
                               'instr': 'apresentador',
                               'key': '',
                               'lead': '',
                               'narr': 'começo da fala aqui neste momento',
                               'type': 'orig',
                               'zoom': False},
                              {'instr': 'inserção de vídeo: y',
                               'key': '',
                               'lead': '',
                               'narr': '',
                               'type': 'insert',
                               'zoom': False},
                              {'instr': 'logo da marca',
                               'key': '',
                               'lead': '',
                               'narr': 'marca e nome do',
                               'type': 'logo',
                               'zoom': False},
                              {'_base': 1.0,
                               'instr': 'apresentador + lettering',
                               'key': 'DESTAQUE',
                               'lead': '',
                               'narr': 'texto de destaque',
                               'type': 'lettering',
                               'zoom': False},
                              {'_base': 1.14,
                               'instr': 'apresentador',
                               'key': '',
                               'lead': '',
                               'narr': 'fecho final da fala',
                               'type': 'orig',
                               'zoom': False}],
                   'spans': [[0.0, 2.0], [2.0, 2.3], [2.3, 3.7], [3.7, 4.8], [4.8, 6.27]],
                   'bwords': [[[0.0, 0.27],
                               [0.3, 0.57],
                               [0.6, 0.87],
                               [0.9, 1.17],
                               [1.2, 1.47],
                               [1.5, 1.77]],
                              [[2.0, 2.27]],
                              [[2.3, 2.57], [2.6, 2.87], [2.9, 3.17], [3.2, 3.47]],
                              [[3.7, 3.97], [4.0, 4.27], [4.3, 4.57]],
                              [[4.8, 5.07], [5.1, 5.37], [5.4, 5.67], [5.7, 5.97]]],
                   'plano': [{'bloco': 0,
                              'crop': None,
                              'de': 1,
                              'e': 2.0,
                              's': 0.0,
                              'sub': 0,
                              'tipo': 'orig'},
                             {'bloco': 1,
                              'crop': None,
                              'de': 1,
                              'e': 2.3,
                              's': 2.0,
                              'sub': 0,
                              'tipo': 'insert'},
                             {'bloco': 2,
                              'crop': None,
                              'de': 1,
                              'e': 3.7,
                              's': 2.3,
                              'sub': 0,
                              'tipo': 'orig'},
                             {'bloco': 3,
                              'crop': None,
                              'de': 1,
                              'e': 4.8,
                              's': 3.7,
                              'sub': 0,
                              'tipo': 'orig'},
                             {'bloco': 4,
                              'crop': None,
                              'de': 1,
                              'e': 6.27,
                              's': 4.8,
                              'sub': 0,
                              'tipo': 'orig'}],
                   'bases': [1.0, None, None, 1.0, 1.14]},
 'sobreposicao': {'blocos_entrada': [{'instr': 'apresentador',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'um dois três quatro cinco seis',
                                      'type': 'orig',
                                      'zoom': False},
                                     {'instr': 'inserção de vídeo: x',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'sete oito nove dez onze doze treze',
                                      'type': 'insert',
                                      'zoom': False},
                                     {'instr': 'apresentador',
                                      'key': '',
                                      'lead': '',
                                      'narr': 'catorze quinze dezesseis',
                                      'type': 'orig',
                                      'zoom': False}],
                  'palavras': [[0.0, 0.27, 'um'],
                               [0.3, 0.57, 'dois'],
                               [0.6, 0.87, 'três'],
                               [0.9, 1.17, 'quatro'],
                               [1.2, 1.47, 'cinco'],
                               [1.5, 1.77, 'seis'],
                               [1.3, 1.57, 'sete'],
                               [1.6, 1.87, 'oito'],
                               [1.9, 2.17, 'nove'],
                               [2.2, 2.47, 'dez'],
                               [2.5, 2.77, 'onze'],
                               [2.8, 3.07, 'doze'],
                               [3.1, 3.37, 'treze'],
                               [2.5, 2.77, 'catorze'],
                               [2.8, 3.07, 'quinze'],
                               [3.1, 3.37, 'dezesseis']],
                  'inserts': {'x': {'file': '/m/x.mp4', 'speed': 1.5, 'start': 3}},
                  'blocks': [{'_base': 1.0,
                              'instr': 'apresentador',
                              'key': '',
                              'lead': '',
                              'narr': 'um dois três quatro',
                              'type': 'orig',
                              'zoom': False},
                             {'instr': 'inserção de vídeo: x',
                              'key': '',
                              'lead': '',
                              'narr': 'sete oito nove dez',
                              'type': 'insert',
                              'zoom': False},
                             {'_base': 1.0,
                              'instr': 'apresentador',
                              'key': '',
                              'lead': '',
                              'narr': 'catorze quinze',
                              'type': 'orig',
                              'zoom': False}],
                  'spans': [[0.0, 1.3], [1.3, 2.5], [2.5, 3.37]],
                  'bwords': [[[0.0, 0.27], [0.3, 0.57], [0.6, 0.87], [0.9, 1.17]],
                             [[1.3, 1.57], [1.6, 1.87], [1.9, 2.17], [2.2, 2.47]],
                             [[2.5, 2.77], [2.8, 3.07]]],
                  'plano': [{'bloco': 0,
                             'crop': None,
                             'de': 1,
                             'e': 1.3,
                             's': 0.0,
                             'sub': 0,
                             'tipo': 'orig'},
                            {'bloco': 1,
                             'crop': None,
                             'de': 1,
                             'e': 2.5,
                             's': 1.3,
                             'sub': 0,
                             'tipo': 'insert'},
                            {'bloco': 2,
                             'crop': None,
                             'de': 1,
                             'e': 3.37,
                             's': 2.5,
                             'sub': 0,
                             'tipo': 'orig'}],
                  'bases': [1.0, None, 1.0]}}

# nome -> {json, narr, audio_dur, palavras}
GOLDEN_ALINHAR = {'acento_caixa_e_pontuacao': {'audio_dur': 1.5,
                              'json': {'sentences': [{'tokens': [{'end': 0.4,
                                                                  'start': 0.1,
                                                                  'text': ' Você'},
                                                                 {'end': 0.8,
                                                                  'start': 0.5,
                                                                  'text': ' pode,'},
                                                                 {'end': 1.2,
                                                                  'start': 0.9,
                                                                  'text': ' né?'}]}]},
                              'narr': ['voce', 'pode', 'ne'],
                              'palavras': [[0.1, 0.4, 'voce'],
                                           [0.5, 0.8, 'pode'],
                                           [0.9, 1.2, 'ne']]},
 'cabeca_sem_casamento': {'audio_dur': 5.0,
                          'json': {'sentences': [{'tokens': [{'end': 2.4,
                                                              'start': 2.0,
                                                              'text': ' tres'},
                                                             {'end': 2.9,
                                                              'start': 2.5,
                                                              'text': ' quatro'}]}]},
                          'narr': ['um', 'dois', 'tres', 'quatro'],
                          'palavras': [[1.82, 2.0, 'um'],
                                       [2.0, 2.18, 'dois'],
                                       [2.0, 2.4, 'tres'],
                                       [2.5, 2.9, 'quatro']]},
 'cabeca_sem_casamento_perto_de_zero': {'audio_dur': 2.0,
                                        'json': {'sentences': [{'tokens': [{'end': 0.4,
                                                                            'start': 0.1,
                                                                            'text': ' tres'}]}]},
                                        'narr': ['um', 'tres'],
                                        'palavras': [[0.0, 0.1, 'um'], [0.1, 0.4, 'tres']]},
 'cauda_sem_casamento': {'audio_dur': 5.0,
                         'json': {'sentences': [{'tokens': [{'end': 0.3,
                                                             'start': 0.0,
                                                             'text': ' um'},
                                                            {'end': 0.7,
                                                             'start': 0.4,
                                                             'text': ' dois'}]}]},
                         'narr': ['um', 'dois', 'tres', 'quatro'],
                         'palavras': [[0.0, 0.3, 'um'],
                                      [0.4, 0.7, 'dois'],
                                      [0.7, 4.95, 'tres'],
                                      [4.95, 5.0, 'quatro']]},
 'duas_sem_casamento_com_vizinha_colada': {'audio_dur': 3.0,
                                           'json': {'sentences': [{'tokens': [{'end': 0.5,
                                                                               'start': 0.0,
                                                                               'text': ' um'},
                                                                              {'end': 0.9,
                                                                               'start': 0.5,
                                                                               'text': ' '
                                                                                       'quatro'}]}]},
                                           'narr': ['um', 'dois', 'tres', 'quatro'],
                                           'palavras': [[0.0, 0.5, 'um'],
                                                        [0.5, 0.6799999999999999, 'dois'],
                                                        [0.6799999999999999,
                                                         0.8599999999999999,
                                                         'tres'],
                                                        [0.5, 0.9, 'quatro']]},
 'exato_com_token_partido': {'audio_dur': 2.0,
                             'json': {'sentences': [{'end': 2.0,
                                                     'start': 0.0,
                                                     'text': 'Agora eu vejo',
                                                     'tokens': [{'end': 0.3,
                                                                 'start': 0.0,
                                                                 'text': ' Ag'},
                                                                {'end': 0.6,
                                                                 'start': 0.3,
                                                                 'text': 'ora'},
                                                                {'end': 0.9,
                                                                 'start': 0.7,
                                                                 'text': ' eu'},
                                                                {'end': 1.4,
                                                                 'start': 1.0,
                                                                 'text': ' vejo'}]}]},
                             'narr': ['Agora', 'eu', 'vejo'],
                             'palavras': [[0.0, 0.6, 'Agora'],
                                          [0.7, 0.9, 'eu'],
                                          [1.0, 1.4, 'vejo']]},
 'nada_casa': {'audio_dur': 4.0,
               'json': {'sentences': [{'tokens': [{'end': 0.3, 'start': 0.0, 'text': ' xis'},
                                                  {'end': 0.8,
                                                   'start': 0.4,
                                                   'text': ' ipsilon'}]}]},
               'narr': ['a', 'b', 'c'],
               'palavras': [[3.77, 3.95, 'a'], [3.95, 4.13, 'b'], [3.95, 4.0, 'c']]},
 'palavra_no_meio_sem_casamento': {'audio_dur': 3.0,
                                   'json': {'sentences': [{'tokens': [{'end': 0.3,
                                                                       'start': 0.0,
                                                                       'text': ' um'},
                                                                      {'end': 1.8,
                                                                       'start': 1.5,
                                                                       'text': ' tres'}]}]},
                                   'narr': ['um', 'dois', 'tres'],
                                   'palavras': [[0.0, 0.3, 'um'],
                                                [0.3, 1.5, 'dois'],
                                                [1.5, 1.8, 'tres']]},
 'token_vazio_ignorado': {'audio_dur': 1.0,
                          'json': {'sentences': [{'tokens': [{'end': 0.3,
                                                              'start': 0.0,
                                                              'text': ' um'},
                                                             {'end': 0.4,
                                                              'start': 0.3,
                                                              'text': '  '},
                                                             {'end': 0.8,
                                                              'start': 0.5,
                                                              'text': ' dois'}]}]},
                          'narr': ['um', 'dois'],
                          'palavras': [[0.0, 0.3, 'um'], [0.5, 0.8, 'dois']]},
 'tokens_fora_de_ordem_e_aninhados': {'audio_dur': 2.0,
                                      'json': {'a': {'b': [{'tokens': [{'end': 1.3,
                                                                        'start': 1.0,
                                                                        'text': ' dois'}]},
                                                           {'tokens': [{'end': 0.4,
                                                                        'start': 0.0,
                                                                        'text': ' um'}]}]}},
                                      'narr': ['um', 'dois'],
                                      'palavras': [[0.0, 0.4, 'um'], [1.0, 1.3, 'dois']]}}


def _viaja(obj):
    """tuplas viram listas, como no JSON do golden"""
    return json.loads(json.dumps(obj))


def _roda(cenario):
    blocos = json.loads(json.dumps(cenario["blocos_entrada"]))
    palavras = [tuple(p) for p in cenario["palavras"]]
    inserts = cenario["inserts"]
    spans, bwords = BL.atribuir_spans(blocos, palavras)
    spans = BL.tornar_contiguos(spans)
    blocks, spans, bwords, plano = BL.aplicar_ritmo(blocos, spans, bwords, inserts)
    BL.decidir_bases(blocks)
    return blocks, spans, bwords, plano


@pytest.mark.parametrize("nome", sorted(GOLDEN_CENARIOS))
def test_blocos_spans_palavras_plano_e_bases_batem_com_o_original(nome):
    g = GOLDEN_CENARIOS[nome]
    blocks, spans, bwords, plano = _roda(g)
    assert _viaja(blocks) == g["blocks"]
    assert _viaja(spans) == g["spans"]
    assert _viaja(bwords) == g["bwords"]
    assert _viaja(plano) == g["plano"]
    assert [b.get("_base") for b in blocks] == g["bases"]


@pytest.mark.parametrize("nome", sorted(GOLDEN_CENARIOS))
def test_spans_sao_contiguos_e_crescentes(nome):
    _, spans, _, _ = _roda(GOLDEN_CENARIOS[nome])
    for (a0, a1), (b0, b1) in zip(spans, spans[1:]):
        assert a1 == pytest.approx(b0), "a cadeia posiciona por soma de durações: tem que ser contíguo"
    assert all(e > s for s, e in spans)


# ------------------------------------------------------------------ contiguidade

def test_fronteira_do_bloco_e_o_inicio_da_primeira_palavra_do_seguinte():
    spans = [(0.0, 1.0), (1.4, 2.0), (2.5, 3.0)]            # pausas de 0,4 e 0,5
    assert BL.tornar_contiguos(spans) == [(0.0, 1.4), (1.4, 2.5), (2.5, 3.0)]


def test_sobreposicao_corta_o_rabo_do_bloco_atual():
    spans = [(0.0, 2.0), (1.5, 3.0)]                        # o fuzz do ASR invade 0,5 s
    assert BL.tornar_contiguos(spans) == [(0.0, 1.5), (1.5, 3.0)]


def test_duracao_minima_de_0_3_s_por_bloco():
    spans = [(0.0, 1.0), (0.1, 2.0), (0.15, 3.0)]
    out = BL.tornar_contiguos(spans)
    assert out[0] == (0.0, 0.3) and out[1] == (0.3, 0.6)
    assert all(e - s >= 0.3 - 1e-9 for s, e in out)


# ------------------------------------------------------------------ atribuição de spans

def test_cada_bloco_ganha_as_palavras_que_a_narracao_contou():
    blocos = [{"narr": "a b"}, {"narr": "c"}]
    palavras = [(0.0, 0.2, "a"), (0.3, 0.5, "b"), (0.6, 0.9, "c")]
    spans, bw = BL.atribuir_spans(blocos, palavras)
    assert spans == [(0.0, 0.5), (0.6, 0.9)]
    assert bw == [[(0.0, 0.2), (0.3, 0.5)], [(0.6, 0.9)]]


def test_bloco_sem_narracao_pega_uma_palavra_e_fim_nao_antes_do_inicio():
    blocos = [{"narr": ""}, {"narr": "x y"}]
    palavras = [(1.0, 1.2, "x"), (1.3, 1.5, "y")]
    spans, _ = BL.atribuir_spans(blocos, palavras)
    assert spans[0] == (1.0, 1.2)


def test_span_de_fim_menor_que_inicio_vira_0_6_s():
    blocos = [{"narr": "a"}]
    spans, _ = BL.atribuir_spans(blocos, [(2.0, 2.0, "a")])
    assert spans == [(2.0, 2.6)]


# ------------------------------------------------------------------ inserts

def test_insert_casa_por_palavra_chave_sem_ligar_pra_caixa():
    ins = {"demo a": {"file": "a.mp4"}, "demo b": {"file": "b.mp4"}}
    assert BL.achar_insert(ins, "Inserção de vídeo: DEMO B") == {"file": "b.mp4"}


def test_insert_que_nao_casa_da_erro_alto_e_nao_troca_de_asset():
    ins = {"demo a": {"file": "a.mp4"}}
    with pytest.raises(CA.ErroFootage) as e:
        BL.achar_insert(ins, "inserção de vídeo: outra coisa")
    msg = str(e.value)
    assert "outra coisa" in msg and "demo a" in msg
    assert "Trocar de asset em silencio" in msg


def test_sem_mapa_de_inserts_o_erro_diz_como_declarar():
    with pytest.raises(CA.ErroFootage) as e:
        BL.achar_insert({}, "inserção de vídeo: x")
    assert "VAM_INSERTS_JSON" in str(e.value)


def test_carregar_inserts_le_o_json_ou_devolve_vazio(tmp_path):
    p = tmp_path / "ins.json"
    p.write_text(json.dumps({"k": {"file": "f.mp4", "speed": 1.5}}), encoding="utf-8")
    assert BL.carregar_inserts(str(p)) == {"k": {"file": "f.mp4", "speed": 1.5}}
    assert BL.carregar_inserts(None) == {}


def test_cfg_do_insert_leva_layout_crop_e_fonte_do_plano_de_ritmo():
    ins = {"k": {"file": "f.mp4", "speed": 2.0, "start": 1.0}}
    b = {"instr": "x k", "_layout": "cheio", "_crop": "800:600:0:0", "_fonte_off": 1.5}
    cfg = BL.preparar_insert_cfg(b, ins)
    assert cfg["_layout"] == "cheio"
    assert cfg["crop"] == "800:600:0:0"
    assert cfg["start"] == pytest.approx(1.0 + 1.5 * 2.0)       # offset em tempo de FONTE: multiplica pela velocidade
    assert ins["k"] == {"file": "f.mp4", "speed": 2.0, "start": 1.0}   # o mapa original não é alterado


# ------------------------------------------------------------------ alinhamento

@pytest.mark.parametrize("nome", sorted(GOLDEN_ALINHAR))
def test_alinhamento_casa_palavra_a_palavra_como_o_original(nome):
    g = GOLDEN_ALINHAR[nome]
    out = BL.alinhar_palavras(g["json"], g["narr"], g["audio_dur"])
    assert _viaja(out) == g["palavras"]


def test_alinhar_roda_ffmpeg_parakeet_e_ffprobe_nessa_ordem(tmp_path):
    g = GOLDEN_ALINHAR["exato_com_token_partido"]
    chamadas = []

    def run(cmd):
        chamadas.append([str(c) for c in cmd])
        if "parakeet" in str(cmd[0]):
            (tmp_path / "av.json").write_text(json.dumps(g["json"]), encoding="utf-8")

    def duracao(avatar):
        chamadas.append(["ffprobe", avatar])
        return g["audio_dur"]

    out = BL.alinhar("/AV/avatar.mp4", g["narr"], str(tmp_path), executavel="/falso/bin/parakeet-mlx",
                     run=run, duracao=duracao)
    assert _viaja(out) == g["palavras"]
    assert chamadas[0] == ["ffmpeg", "-y", "-i", "/AV/avatar.mp4", "-vn", "-ac", "1", "-ar", "16000",
                           str(tmp_path / "av.wav")]
    assert chamadas[1] == ["/falso/bin/parakeet-mlx", str(tmp_path / "av.wav"), "--output-format", "json",
                           "--output-dir", str(tmp_path)]
    assert chamadas[2][0] == "ffprobe"


# ------------------------------------------------------------------ parakeet (defeito 3)

def _amb(achados, bins=()):
    return T.Ambiente(sistema="Darwin", arquitetura="arm64", env={},
                      which=lambda nome: achados.get(nome), importavel=lambda m: False, bins_venv=bins)


def test_executavel_do_parakeet_vem_do_backend_de_audio():
    amb = _amb({"parakeet-mlx": "/opt/x/bin/parakeet-mlx"})
    assert BL.executavel_parakeet(amb) == "/opt/x/bin/parakeet-mlx"


def test_executavel_do_parakeet_acha_no_venv(tmp_path):
    exe = tmp_path / "parakeet-mlx"
    exe.write_text("#!/bin/sh\n")
    exe.chmod(0o755)
    assert BL.executavel_parakeet(_amb({}, bins=[tmp_path])) == str(exe)


def test_sem_parakeet_a_mensagem_traz_o_comando_que_resolve(home_falso):
    with pytest.raises(CA.ErroFootage) as e:
        BL.executavel_parakeet(_amb({}))
    msg = str(e.value)
    assert "parakeet-mlx" in msg and "pip install parakeet-mlx" in msg


def test_nunca_mais_procura_o_parakeet_em_local_bin_cravado(home_falso):
    """Com HOME falso o ~/.local/bin do aluno não existe: o caminho não pode depender dele."""
    local = home_falso / ".local" / "bin"
    local.mkdir(parents=True)
    (local / "parakeet-mlx").write_text("#!/bin/sh\n")
    (local / "parakeet-mlx").chmod(0o755)
    with pytest.raises(CA.ErroFootage):
        BL.executavel_parakeet(_amb({}))                      # existe em ~/.local/bin e mesmo assim não vale
    fonte = Path(BL.__file__).read_text(encoding="utf-8")
    assert ".local/bin" not in fonte
